[project]
name = 'Blockchain-Enabled-Forestry-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.harvesting-permit]
path = 'contracts/harvesting-permit.clar'
clarity_version = 2
epoch = 2.5

[contracts.land-parcel-registration]
path = 'contracts/land-parcel-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.reforestation-verification]
path = 'contracts/reforestation-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
